name: CI Python Pablo Reyes

on:
  # 1. Esto se ejecuta automáticamente al hacer push a la rama 'reyes'
push:
    branches: [ reyes ]  
  pull_request:
    branches: [ reyes ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: ⬇Checkout del Codigo
      uses: actions/checkout@v3

    - name: Configuracion del Entorno Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependencias
      run: pip install -r requirements.txt

    - name: Ejecutar Pruebas (Debe Fallar)
      run: pytest test_area.py