# .github/workflows/ci-python.yml
name: CI Python Pablo Reyes

on:
  push:
    # CRÍTICO: La rama de trabajo del examen es 'reyes'
    branches: [ reyes ] 
  pull_request:
    branches: [ reyes ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: ⬇Checkout del Codigo
      uses: actions/checkout@v3

    - name: Configuracion del Entorno Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependencias
      run: pip install -r requirements.txt

    - name: Ejecutar Pruebas (Debe Pasar)
      run: pytest test_area.py